const Employee = require('../lib/employee.js');


describe("Engineer", () => {
    describe('ExportAssignment', () => {
        it('should properly export Values to new files', () => {
            const name = 'Daisy Bloom';
            const id = '465838';
            const email = 'Daisybloom@imdengineering.com';
            const employee = new Employee(name, id, email);
        
            expect(employee.name).toBe('Daisy Bloom');
            // The program runs a test to verify that the name entered by the user matches the output generated by a function.
            expect(employee.id).toBe('465838');
            // executes a test to validate whether the ID provided by the user matches the output produced by a function.
            expect(employee.email).toBe('Daisybloom@imdengineering.com');
            //  performs a test to verify that the email inputted by the user corresponds to the output created by a function.
        });
    });
});